# Generated by Django 5.2.3 on 2025-06-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_custom_password_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
