# Generated by Django 5.2.3 on 2025-06-29 13:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_type', models.CharField(choices=[('access', 'Access Token'), ('refresh', 'Refresh Token')], max_length=10, verbose_name='Token Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('logged_out', 'Logged Out')], default='active', max_length=15, verbose_name='Status')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('device_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Device Info')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Authentication Session',
                'verbose_name_plural': 'Authentication Sessions',
                'db_table': 'auth_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='auth_sessio_user_id_83c7b0_idx'), models.Index(fields=['token_type', 'status'], name='auth_sessio_token_t_2eb865_idx'), models.Index(fields=['expires_at'], name='auth_sessio_expires_81dfbf_idx'), models.Index(fields=['created_at'], name='auth_sessio_created_a43de4_idx'), models.Index(fields=['user', 'token_type', 'status'], name='auth_sessio_user_id_aee278_idx')],
            },
        ),
    ]
